id: P006790
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:23:04.399352
source_metadata:
  id: bdr:W4CZ34267
  title: ཚད་མ་རྣམ་འགྲེལ་ལེགས་པར་བཤད་པ།
  author: ''
  volumes:
    27da43c57e0e457c9d0558866fd728ab:
      image_group_id: I4CZ45302
      title: ''
      volume_number: 1
      total_pages: 281
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
