id: IAF34D1BA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T23:09:50+00:00'
last_modified: '2022-06-08T06:52:39.475192+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ34267
  title: ཚད་མ་རྣམ་འགྲེལ་ལེགས་པར་བཤད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    331B:
      image_group_id: I4CZ45302
      title: ''
      total_pages: 281
      order: 1
      base_file: 331B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
